### ISSUE TITLE
Header format in test binary

### ISSUE THREAD

**Issue by jteeuwen** [Zoclee/Shade#1]
Hello!

I found that the header in the test binary is missing the `Reserved` field as defined in chapter 2.3 (Physical Layout of a SPIR-V Module and Instruction) of the spec.
It's value should be `0` but it is not optional.

As it stands the header looks like:

```
03 02 23 07    // Magic number
63 00 00 00    // Version (99)
1B 00 00 00    // GeneratorMagic (27)
17 00 00 00    // Bound (23)
```

It is then immediately followed by the `OpSource` instruction, where it should have the `Reserved` field.

**Comment by alwyn1024** [comment]
Thank you for pointing out this error. It's been fixed and the new binary is available for download.
